from __future__ import annotations

import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

GAMMA_API_URL = "https://gamma-api.polymarket.com"
CLOB_API_URL = "https://clob.polymarket.com"

DATABASE_URL = os.getenv("POLYMARKET_DATABASE_URL", "").strip()
DB_BACKEND = os.getenv("POLYMARKET_DB_BACKEND", "postgres" if DATABASE_URL else "sqlite").strip().lower()
DB_PATH = os.getenv("POLYMARKET_SQLITE_PATH", str(REPO_ROOT / "database" / "polymarket_state.db"))


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return int(raw.strip())
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return float(raw.strip())
    except ValueError:
        return default


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_csv(name: str, default: tuple[str, ...]) -> tuple[str, ...]:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    values = tuple(item.strip() for item in raw.split(",") if item.strip())
    return values or default


REDIS_URL = os.getenv("POLYMARKET_REDIS_URL", "redis://localhost:6379/0").strip()
PHASE3_STATE_BACKEND = os.getenv("POLYMARKET_PHASE3_STATE_BACKEND", "redis").strip().lower()
PHASE3_FEATURE_SCHEMA_VERSION = os.getenv(
    "POLYMARKET_PHASE3_FEATURE_SCHEMA_VERSION",
    "phase3_v1",
).strip()
PHASE3_DETECTOR_VERSION = os.getenv(
    "POLYMARKET_PHASE3_DETECTOR_VERSION",
    "phase3_detector_v1",
).strip()
PHASE3_WINDOW_SECONDS = _env_int("POLYMARKET_PHASE3_WINDOW_SECONDS", 300)
PHASE3_HISTORY_SECONDS = _env_int("POLYMARKET_PHASE3_HISTORY_SECONDS", 600)
PHASE3_COOLDOWN_SECONDS = _env_int("POLYMARKET_PHASE3_COOLDOWN_SECONDS", 900)
PHASE3_MIN_FRESH_WALLET_COUNT = _env_int("POLYMARKET_PHASE3_MIN_FRESH_WALLET_COUNT", 3)
PHASE3_MIN_FRESH_WALLET_NOTIONAL_SHARE = _env_float(
    "POLYMARKET_PHASE3_MIN_FRESH_WALLET_NOTIONAL_SHARE",
    0.35,
)
PHASE3_MIN_DIRECTIONAL_IMBALANCE = _env_float(
    "POLYMARKET_PHASE3_MIN_DIRECTIONAL_IMBALANCE",
    0.65,
)
PHASE3_MIN_CONCENTRATION_RATIO = _env_float(
    "POLYMARKET_PHASE3_MIN_CONCENTRATION_RATIO",
    0.45,
)
PHASE3_MIN_PROBABILITY_VELOCITY = _env_float(
    "POLYMARKET_PHASE3_MIN_PROBABILITY_VELOCITY",
    0.02,
)
PHASE3_MIN_PROBABILITY_ACCELERATION = _env_float(
    "POLYMARKET_PHASE3_MIN_PROBABILITY_ACCELERATION",
    0.005,
)
PHASE3_MIN_VOLUME_ACCELERATION = _env_float(
    "POLYMARKET_PHASE3_MIN_VOLUME_ACCELERATION",
    1.25,
)
PHASE3_MIN_WINDOW_NOTIONAL = _env_float(
    "POLYMARKET_PHASE3_MIN_WINDOW_NOTIONAL",
    250.0,
)
PHASE3_POLL_SECONDS = _env_float("POLYMARKET_PHASE3_POLL_SECONDS", 5.0)
ENABLE_PHASE3_DETECTOR = _env_bool("POLYMARKET_ENABLE_PHASE3_DETECTOR", False)
PHASE3_SOURCE_SYSTEMS = _env_csv(
    "POLYMARKET_PHASE3_SOURCE_SYSTEMS",
    ("clob_ws_market", "data_api_trades", "data_api_trades_backfill", "clob_prices", "clob_books"),
)

PHASE4_WORKFLOW_VERSION = os.getenv(
    "POLYMARKET_PHASE4_WORKFLOW_VERSION",
    "phase4_alerts_v1",
).strip()
PHASE4_EVIDENCE_SCHEMA_VERSION = os.getenv(
    "POLYMARKET_PHASE4_EVIDENCE_SCHEMA_VERSION",
    "phase4_evidence_v1",
).strip()
PHASE4_ALERT_SCHEMA_VERSION = os.getenv(
    "POLYMARKET_PHASE4_ALERT_SCHEMA_VERSION",
    "phase4_alert_payload_v1",
).strip()
PHASE4_EVIDENCE_TIMEOUT_SECONDS = _env_int(
    "POLYMARKET_PHASE4_EVIDENCE_TIMEOUT_SECONDS",
    10,
)
PHASE4_EVIDENCE_CACHE_TTL_SECONDS = _env_int(
    "POLYMARKET_PHASE4_EVIDENCE_CACHE_TTL_SECONDS",
    900,
)
PHASE4_ALERT_SUPPRESSION_SECONDS = _env_int(
    "POLYMARKET_PHASE4_ALERT_SUPPRESSION_SECONDS",
    1800,
)
PHASE4_ALERT_INFO_THRESHOLD = _env_float(
    "POLYMARKET_PHASE4_ALERT_INFO_THRESHOLD",
    0.25,
)
PHASE4_ALERT_WATCH_THRESHOLD = _env_float(
    "POLYMARKET_PHASE4_ALERT_WATCH_THRESHOLD",
    0.5,
)
PHASE4_ALERT_ACTIONABLE_THRESHOLD = _env_float(
    "POLYMARKET_PHASE4_ALERT_ACTIONABLE_THRESHOLD",
    0.8,
)
PHASE4_ALERT_CHANNELS = _env_csv(
    "POLYMARKET_PHASE4_ALERT_CHANNELS",
    ("telegram", "discord"),
)
PHASE4_EVIDENCE_PROVIDERS = _env_csv(
    "POLYMARKET_PHASE4_EVIDENCE_PROVIDERS",
    ("noop_news", "noop_social"),
)
ENABLE_PHASE4_TELEGRAM = _env_bool("POLYMARKET_ENABLE_PHASE4_TELEGRAM", False)
ENABLE_PHASE4_DISCORD = _env_bool("POLYMARKET_ENABLE_PHASE4_DISCORD", False)
PHASE4_TELEGRAM_BOT_TOKEN = os.getenv("POLYMARKET_PHASE4_TELEGRAM_BOT_TOKEN", "").strip()
PHASE4_TELEGRAM_CHAT_ID = os.getenv("POLYMARKET_PHASE4_TELEGRAM_CHAT_ID", "").strip()
PHASE4_DISCORD_WEBHOOK_URL = os.getenv("POLYMARKET_PHASE4_DISCORD_WEBHOOK_URL", "").strip()

PHASE5_BACKFILL_REQUEST_LIMIT = _env_int("POLYMARKET_PHASE5_BACKFILL_REQUEST_LIMIT", 10)
PHASE5_BACKFILL_MARKET_LIMIT = _env_int("POLYMARKET_PHASE5_BACKFILL_MARKET_LIMIT", 0)
PHASE5_SIMULATOR_VERSION = os.getenv(
    "POLYMARKET_PHASE5_SIMULATOR_VERSION",
    "phase5_simulator_v1",
).strip()
PHASE5_METRICS_VERSION = os.getenv(
    "POLYMARKET_PHASE5_METRICS_VERSION",
    "phase5_metrics_v1",
).strip()
PHASE5_REPORT_VERSION = os.getenv(
    "POLYMARKET_PHASE5_REPORT_VERSION",
    "phase5_report_v1",
).strip()
PHASE5_EVENT_FAMILY_FOLDS = _env_int("POLYMARKET_PHASE5_EVENT_FAMILY_FOLDS", 5)
PHASE5_TIME_BLOCK_DAYS = _env_int("POLYMARKET_PHASE5_TIME_BLOCK_DAYS", 30)
PHASE5_MIN_CANDIDATE_ROWS = _env_int("POLYMARKET_PHASE5_MIN_CANDIDATE_ROWS", 30)
PHASE5_MIN_ALERT_ROWS = _env_int("POLYMARKET_PHASE5_MIN_ALERT_ROWS", 20)
PHASE5_MIN_PAPER_TRADE_ROWS = _env_int("POLYMARKET_PHASE5_MIN_PAPER_TRADE_ROWS", 10)
PHASE5_MIN_DISTINCT_EVENT_FAMILIES = _env_int(
    "POLYMARKET_PHASE5_MIN_DISTINCT_EVENT_FAMILIES",
    5,
)
PHASE5_MIN_DISTINCT_CATEGORIES = _env_int(
    "POLYMARKET_PHASE5_MIN_DISTINCT_CATEGORIES",
    3,
)
PHASE5_MIN_RESOLVED_ROWS = _env_int("POLYMARKET_PHASE5_MIN_RESOLVED_ROWS", 15)
PHASE5_MIN_COVERAGE_RATIO = _env_float("POLYMARKET_PHASE5_MIN_COVERAGE_RATIO", 0.80)
PHASE5_TICK_SIZE = _env_float("POLYMARKET_PHASE5_TICK_SIZE", 0.01)
PHASE5_ENTRY_SLIPPAGE_TICKS = _env_int("POLYMARKET_PHASE5_ENTRY_SLIPPAGE_TICKS", 1)
PHASE5_EXIT_SLIPPAGE_TICKS = _env_int("POLYMARKET_PHASE5_EXIT_SLIPPAGE_TICKS", 1)
PHASE5_FEE_RATE = _env_float("POLYMARKET_PHASE5_FEE_RATE", 0.02)
PHASE5_MAX_TRADE_NOTIONAL = _env_float("POLYMARKET_PHASE5_MAX_TRADE_NOTIONAL", 100.0)
PHASE5_MAX_CONCURRENT_GLOBAL = _env_int("POLYMARKET_PHASE5_MAX_CONCURRENT_GLOBAL", 5)
PHASE5_MAX_CONCURRENT_EVENT_FAMILY = _env_int(
    "POLYMARKET_PHASE5_MAX_CONCURRENT_EVENT_FAMILY",
    1,
)
PHASE5_MAX_HOLDING_HOURS = _env_int("POLYMARKET_PHASE5_MAX_HOLDING_HOURS", 24)
PHASE5_NEAR_RESOLUTION_MINUTES = _env_int(
    "POLYMARKET_PHASE5_NEAR_RESOLUTION_MINUTES",
    60,
)
PHASE5_RISK_STOP_LOSS_FRACTION = _env_float(
    "POLYMARKET_PHASE5_RISK_STOP_LOSS_FRACTION",
    0.20,
)
PHASE5_DIRECTION_MIN_ABS_VELOCITY = _env_float(
    "POLYMARKET_PHASE5_DIRECTION_MIN_ABS_VELOCITY",
    0.0,
)

PHASE6_FEATURE_SCHEMA_VERSION = os.getenv(
    "POLYMARKET_PHASE6_FEATURE_SCHEMA_VERSION",
    "phase6_features_v1",
).strip()
PHASE6_MODEL_REGISTRY_VERSION = os.getenv(
    "POLYMARKET_PHASE6_MODEL_REGISTRY_VERSION",
    "phase6_registry_v1",
).strip()
PHASE6_DEFAULT_MODEL_NAME = os.getenv(
    "POLYMARKET_PHASE6_DEFAULT_MODEL_NAME",
    "phase6_ranker_v1",
).strip()
PHASE6_EVALUATION_VERSION = os.getenv(
    "POLYMARKET_PHASE6_EVALUATION_VERSION",
    "phase6_eval_v1",
).strip()
PHASE6_CALIBRATION_VERSION = os.getenv(
    "POLYMARKET_PHASE6_CALIBRATION_VERSION",
    "phase6_calibration_v1",
).strip()
PHASE6_LIQUIDITY_SPREAD_TIGHT = _env_float(
    "POLYMARKET_PHASE6_LIQUIDITY_SPREAD_TIGHT",
    0.02,
)
PHASE6_LIQUIDITY_SPREAD_WIDE = _env_float(
    "POLYMARKET_PHASE6_LIQUIDITY_SPREAD_WIDE",
    0.05,
)
PHASE6_WATCH_PRECISION_TARGET = _env_float(
    "POLYMARKET_PHASE6_WATCH_PRECISION_TARGET",
    0.55,
)
PHASE6_ACTIONABLE_PRECISION_TARGET = _env_float(
    "POLYMARKET_PHASE6_ACTIONABLE_PRECISION_TARGET",
    0.65,
)
PHASE6_CRITICAL_PRECISION_TARGET = _env_float(
    "POLYMARKET_PHASE6_CRITICAL_PRECISION_TARGET",
    0.80,
)
PHASE6_LIVE_LOOKBACK_MINUTES = _env_int(
    "POLYMARKET_PHASE6_LIVE_LOOKBACK_MINUTES",
    30,
)
PHASE6_LIVE_POLL_SECONDS = _env_int(
    "POLYMARKET_PHASE6_LIVE_POLL_SECONDS",
    30,
)
ENABLE_PHASE6_SHADOW_MODE = _env_bool("POLYMARKET_ENABLE_PHASE6_SHADOW_MODE", False)

PHASE7_HOT_RETENTION_DAYS = _env_int(
    "POLYMARKET_PHASE7_HOT_RETENTION_DAYS",
    30,
)
PHASE7_WARM_RETENTION_DAYS = _env_int(
    "POLYMARKET_PHASE7_WARM_RETENTION_DAYS",
    120,
)
PHASE7_COLD_RETENTION_DAYS = _env_int(
    "POLYMARKET_PHASE7_COLD_RETENTION_DAYS",
    365,
)
PHASE7_COMPACTION_MIN_BYTES = _env_int(
    "POLYMARKET_PHASE7_COMPACTION_MIN_BYTES",
    50 * 1024 * 1024,
)
PHASE7_DASHBOARD_TOP_N = _env_int(
    "POLYMARKET_PHASE7_DASHBOARD_TOP_N",
    10,
)
PHASE7_POLICY_BATCH_SIZE = _env_int(
    "POLYMARKET_PHASE7_POLICY_BATCH_SIZE",
    100,
)
PHASE7_PROFILE_STALE_HOURS = _env_int(
    "POLYMARKET_PHASE7_PROFILE_STALE_HOURS",
    24,
)
PHASE7_PROFILE_TOP_N = _env_int(
    "POLYMARKET_PHASE7_PROFILE_TOP_N",
    10,
)
PHASE7_DATASET_INDEX_VERSION = os.getenv(
    "POLYMARKET_PHASE7_DATASET_INDEX_VERSION",
    "phase7_dataset_index_v1",
).strip()
PHASE7_SCOPE_INDEX_VERSION = os.getenv(
    "POLYMARKET_PHASE7_SCOPE_INDEX_VERSION",
    "phase7_scope_index_v1",
).strip()
PHASE7_EXPERIMENT_LEDGER_VERSION = os.getenv(
    "POLYMARKET_PHASE7_EXPERIMENT_LEDGER_VERSION",
    "phase7_experiment_ledger_v1",
).strip()
PHASE7_LABEL_SCHEMA_VERSION = os.getenv(
    "POLYMARKET_PHASE7_LABEL_SCHEMA_VERSION",
    "phase7_labels_v1",
).strip()
PHASE7_DEFAULT_DATASET_ROLE = os.getenv(
    "POLYMARKET_PHASE7_DEFAULT_DATASET_ROLE",
    "advanced_research",
).strip()
PHASE7_DEFAULT_EXPERIMENT_FAMILY = os.getenv(
    "POLYMARKET_PHASE7_DEFAULT_EXPERIMENT_FAMILY",
    "advanced_research",
).strip()
PHASE7_CONFIG_VERSION = os.getenv(
    "POLYMARKET_PHASE7_CONFIG_VERSION",
    "phase7_experiment_config_v1",
).strip()
PHASE7_DEFAULT_RANDOM_SEED = _env_int(
    "POLYMARKET_PHASE7_DEFAULT_RANDOM_SEED",
    17,
)
PHASE7_GRAPH_FEATURE_SCHEMA_VERSION = os.getenv(
    "POLYMARKET_PHASE7_GRAPH_FEATURE_SCHEMA_VERSION",
    "phase7_graph_features_v1",
).strip()
PHASE7_GRAPH_LOOKBACK_DAYS = _env_int(
    "POLYMARKET_PHASE7_GRAPH_LOOKBACK_DAYS",
    90,
)
PHASE7_GRAPH_PERSISTENCE_MIN_DAYS = _env_int(
    "POLYMARKET_PHASE7_GRAPH_PERSISTENCE_MIN_DAYS",
    2,
)
PHASE7_ADVANCED_MODEL_NAME = os.getenv(
    "POLYMARKET_PHASE7_ADVANCED_MODEL_NAME",
    "phase7_graph_ranker",
).strip()
PHASE7_ADVANCED_EXPERIMENT_VERSION = os.getenv(
    "POLYMARKET_PHASE7_ADVANCED_EXPERIMENT_VERSION",
    "phase7_graph_experiment_v1",
).strip()
PHASE7_RESEARCH_PACKAGE_VERSION = os.getenv(
    "POLYMARKET_PHASE7_RESEARCH_PACKAGE_VERSION",
    "phase7_research_package_v1",
).strip()
PHASE7_THESIS_FIGURE_STYLE_VERSION = os.getenv(
    "POLYMARKET_PHASE7_THESIS_FIGURE_STYLE_VERSION",
    "phase7_thesis_figures_v1",
).strip()
